export const FETCH_PRODUCT = 'FETCH_PRODUCT';

export const POST_TRANSACTION = 'POST_TRANSACTION';
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const FETCH_TODAY_TRANSACTION = 'FETCH_TODAY_TRANSACTION';
export const FETCH_TRANSACTION_BY_DATE = 'FETCH_TRANSACTION_BY_DATE';
